### ISSUE TITLE
More Detail: Jared Houseman

### ISSUE THREAD

**Issue by jiviteshkuk26** [Amp-Lab-at-VT/Website#106]
Find out more about the tube stuff and if it is high voltage

**Comment by Forsyth-Creations** [comment]
Covered with #112

**Comment by Forsyth-Creations** [comment]
https://github.com/DavidRajwan/Marksman-H-combat-remote.git
David Rajwan
davidrajwan25@vt.edu
CPE (Computer Engineering)

3D printing materials, motors, camera, infrared sensors, and programable microcontroller board.
Communication protocols between programmable boards, 3D modeling and fabrication, artificial intelligence (Open CV) and algorithm development, software design, mechanical and electronic (mechatronic) design and interdisciplinary integration. 

1-year (Two semesters) to 2-years (Four semesters)
