### ISSUE TITLE
[new-project]: Computer Architecture 8-bit

### ISSUE THREAD

**Issue by Vasilik55** [Amp-Lab-at-VT/Website#138]
### Name

Vasili Konstantinakos, Austin Jobin

### Contact Details

williamkonstantinakos@gmail.com, austinjobin22@vt.edu

### Project Link

N/A

### What is your major?

EE (Electrical Engineering)

### How Long?

2 Semesters

**Comment by epritchard13** [comment]
https://github.com/Amp-Lab-at-VT/Simple-PLC
