### ISSUE TITLE
Fix the link to the AMP Lab webpage on the ECE Design Studio's page

### ISSUE THREAD

**Issue by michael-kricheldorf** [Amp-Lab-at-VT/Website#19]
It links to the old Google Site :(

**Comment by Forsyth-Creations** [comment]
https://sites.google.com/a/vt.edu/ece-design-studio/home

The amp lab button here doesn't link to the correct website

**Comment by Forsyth-Creations** [comment]
This is not a priority anymore. Closing due to lack of need
